services:
  building_1:
    image: mr4x2/mqtt-publisher:v1
    container_name: mqtt-publisher-building-1
    volumes:
      - /mnt/iot-data:/app/data-5-house
    command: "node index.js -f data-5-house/${CSV_FILE_0} -b ${HOST_NAME} -s ${SPEED}"

  building_2:
    image: mr4x2/mqtt-publisher:v1
    container_name: mqtt-publisher-building-2
    volumes:
      - /mnt/iot-data:/app/data-5-house
    command: "node index.js -f data-5-house/${CSV_FILE_1} -b ${HOST_NAME} -s ${SPEED}"

  building_3:
    image: mr4x2/mqtt-publisher:v1
    container_name: mqtt-publisher-building-3
    volumes:
      - /mnt/iot-data:/app/data-5-house
    command: "node index.js -f data-5-house/${CSV_FILE_2} -b ${HOST_NAME} -s ${SPEED}"

  building_4:
    image: mr4x2/mqtt-publisher:v1
    container_name: mqtt-publisher-building-4
    volumes:
      - /mnt/iot-data:/app/data-5-house
    command: "node index.js -f data-5-house/${CSV_FILE_3} -b ${HOST_NAME} -s ${SPEED}"

  building_5:
    image: mr4x2/mqtt-publisher:v1
    container_name: mqtt-publisher-building-5
    volumes:
      - /mnt/iot-data:/app/data-5-house
    command: "node index.js -f data-5-house/${CSV_FILE_4} -b ${HOST_NAME} -s ${SPEED}"
